import { ProposalType } from "../../src/types";
import { makeProposal } from "../../src/utils";

export const BSC_XVS_VAULT = "0x051100480289e704d20e9DB4804837068f3f9204";
export const BSC_XVS = "0xcF6BB5389c92Bdda8a3747Ddb454cB7a64626C63";
export const BSC_XVS_VAULT_RATE = "45520833333333333";

export const vip413 = () => {
  const meta = {
    version: "v2",
    title: "VIP-413 Emissions Adjustments - XVS Vault on BNB Chain",
    description: `If passed, this VIP will update the total XVS distributed by the XVS Vault on BNB Chain, to 1,311 XVS/day (39,330 XVS/month).

The [VIP-410 Emissions Adjustments Across All Chains](https://app.venus.io/#/governance/proposal/410?chainId=56) reduced the total XVS distributed by the XVS Vault on BNB Chain, but the community proposal [Proposal: Emissions Adjustments Across All Chains](https://community.venus.io/t/proposal-emissions-adjustments-across-all-chains/4777), and the [associated snapshot](https://snapshot.box/#/s:venus-xvs.eth/proposal/0x8033a801d152e88511475c117e114a3a2e4037d5a7252a2bea40e78a36b72d51), only proposed to reduce the legacy XVS Vault Base Rewards, from 630 XVS/day (18,900 XVS/month) to 441 XVS/day (13,230 XVS/month), not updating the distribution of the XVS generated by the protocol revenue.

#### References

- [VIP simulation](https://github.com/VenusProtocol/vips/pull/446)`,
    forDescription: "Execute this proposal",
    againstDescription: "Do not execute this proposal",
    abstainDescription: "Indifferent to execution",
  };

  return makeProposal(
    [
      {
        target: BSC_XVS_VAULT,
        signature: "setRewardAmountPerBlockOrSecond(address,uint256)",
        params: [BSC_XVS, BSC_XVS_VAULT_RATE],
      },
    ],
    meta,
    ProposalType.CRITICAL,
  );
};

export default vip413;
