import { parseUnits } from "ethers/lib/utils";
import { ethers } from "hardhat";
import { NETWORK_ADDRESSES } from "src/networkAddresses";
import { LzChainId, ProposalMeta, ProposalType } from "src/types";
import { makeProposal } from "src/utils";

const { bscmainnet, ethereum, arbitrumone, zksyncmainnet, unichainmainnet } = NETWORK_ADDRESSES;

export const ADAPTER_PARAMS = ethers.utils.solidityPack(["uint16", "uint256"], [1, 300000]);
const BRIDGE_FEES = parseUnits("0.5", 18);

export const XVS_VAULT_TREASURY_BSC = "0x269ff7818DB317f60E386D2be0B259e1a324a40a";
export const RELEASE_AMOUNT_BSC = parseUnits("234352", 18);
export const DISTRIBUTION_SPEED_BSC = "25173611111111112"; // 2,900 XVS/day
export const XVS_BRIDGE_BSC = "0xf8F46791E3dB29a029Ec6c9d946226f3c613e854";
export const XVS_STORE_BSC = "0x1e25CF968f12850003Db17E0Dba32108509C4359";

export const XVS_VAULT_TREASURY_ETH = "0xaE39C38AF957338b3cEE2b3E5d825ea88df02EfE";
export const RELEASE_AMOUNT_ETH = parseUnits("1007", 18);
export const DISTRIBUTION_SPEED_ETH = "21527777777777778"; // 155 XVS/day
export const XVS_STORE_ETH = "0x1Db646E1Ab05571AF99e47e8F909801e5C99d37B";

export const XVS_VAULT_TREASURY_ARB = "0xb076D4f15c08D7A7B89466327Ba71bc7e1311b58";
export const RELEASE_AMOUNT_ARB = parseUnits("120", 18);
export const DISTRIBUTION_SPEED_ARB = "305555555555556"; // 26.4 XVS/day
export const XVS_STORE_ARB = "0x507D9923c954AAD8eC530ed8Dedb75bFc893Ec5e";

export const DISTRIBUTION_SPEED_ZKSYNC = "280092592592593"; // 24.2 XVS/day
export const XVS_STORE_ZKSYNC = "0x84266F552756cBed893b1FFA85248cD99501e3ce";

export const DISTRIBUTION_SPEED_UNICHAIN = "77160493827160"; // 6.6 XVS/day

export const XVS_TOTAL_AMOUNT_BSC = parseUnits("56493", 18);
export const XVS_TOTAL_AMOUNT_ETH = parseUnits("10584", 18);
export const XVS_TOTAL_AMOUNT_ARB = parseUnits("2205", 18);
export const XVS_TOTAL_AMOUNT_ZKSYNC = parseUnits("2205", 18);
export const TOTAL_XVS = XVS_TOTAL_AMOUNT_BSC.add(XVS_TOTAL_AMOUNT_ETH)
  .add(XVS_TOTAL_AMOUNT_ARB)
  .add(XVS_TOTAL_AMOUNT_ZKSYNC);
export const TOTAL_XVS_REMOTE = XVS_TOTAL_AMOUNT_ETH.add(XVS_TOTAL_AMOUNT_ARB).add(XVS_TOTAL_AMOUNT_ZKSYNC);

export const vip529 = async () => {
  const meta: ProposalMeta = {
    version: "v2",
    title: "VIP-529 Quarterly XVS Buyback and Funds Allocation",
    description: `#### Summary

This VIP outlines the protocol’s Quarterly Buyback and Funds Allocation strategy as per our [Tokenomics V4](https://snapshot.box/#/s:venus-xvs.eth/proposal/0x21c89f6b5d7c9e453b3bac64b23c1d81fe52ff4f23ba0b64674c34217c3f9245), emphasizing the key aspects for Q2 2025 stated below.

If passed, this VIP will also:

- Transfer 56,493 XVS from the [Core pool Comptroller](https://bscscan.com/address/0xfD36E2c2a6789Db23113685031d7F16329158384) to the XVS Store on BNB for Q3 and Q4 Vault Base Rewards
- Bridge XVS from the [Core pool Comptroller](https://bscscan.com/address/0xfD36E2c2a6789Db23113685031d7F16329158384) to the XVS Stores on Ethereum (10,584 XVS), Arbitrum (2,205 XVS) and ZKSync (2,205 XVS) for Q3 Quarterly Emissions (as per [VIP-471](https://app.venus.io/#/governance/proposal/471)).

**BNB Chain:**

**Protocol Reserves & Liquidation Fees**

- Protocol Reserves: $1,192,657
- Liquidation Fees: $6,503,480 ($6,268,808 were generated by the [liquidation of the account 0x48..9BEC](https://community.venus.io/t/0x48-9bec-account-remediation-concluding-steps/5034))
- Total: $7,696,136

**Tokenomic Allocations:**

- XVS Buyback: $1,539,227 (234,352 XVS)
- Venus Prime: $238,531
- Treasury: $5,918,378

**Ethereum:**

**Protocol Reserves & Liquidation Fees**

- Protocol Reserves: $15,689
- Liquidation Fees: $25,174
- Total: $40,863

**Tokenomic Allocations:**

- XVS Buyback: $6,612 (1,008 XVS)
- Venus Prime: $3,138
- Treasury: $29,553

**Arbitrum one:**

**Protocol Reserves & Liquidation Fees**

- Protocol Reserves: $5,881
- Liquidation Fees: $1,399
- Total: $7,280

**Tokenomic Allocations:**

- XVS Buyback: $787 (120 XVS)
- Venus Prime: $1,176
- Treasury: $4,647

**ZKsync Era:**

**Protocol Reserves & Liquidation Fees**

- Protocol Reserves: $3,094
- Liquidation Fees: $3,842
- Total: $6,937

**Tokenomic Allocations:**

- XVS Buyback: $1,387
- Venus Prime: $619
- Treasury: $4,930

**Unichain:**

**Protocol Reserves & Liquidation Fees**

- Protocol Reserves: $12,833
- Liquidation Fees: $20
- Total: $12,854

**Tokenomic Allocations:**

- XVS Buyback: $2,571
- Venus Prime: $2,567
- Treasury: $7,716

The XVS Buyback was executed gradually over the quarter.

**If approved, this VIP will perform the following actions:**

**BNB Chain:**

- XVS Buyback Allocation: Send the buyback 234,352 XVS from the [XVS Vault Treasury](https://bscscan.com/address/0x269ff7818DB317f60E386D2be0B259e1a324a40a) to the [XVS Store](https://bscscan.com/address/0x1e25CF968f12850003Db17E0Dba32108509C4359), for the new XVS vault rewards.
- XVS Vault Base Rewards: Send 56,493 XVS from the [Core pool Comptroller](https://bscscan.com/address/0xfD36E2c2a6789Db23113685031d7F16329158384) to the [XVS Store](https://bscscan.com/address/0x1e25CF968f12850003Db17E0Dba32108509C4359) on BNB Chain (308.7 XVS/day, for Q3 and Q4, 183 days).
- XVS Vault Speed: Set the new XVS Vault reward speed to **2,900 daily XVS**.

**Ethereum:**

- XVS Buyback Allocation: Send the buyback 1,008 XVS from the [XVS Vault Treasury](https://etherscan.io/address/0xaE39C38AF957338b3cEE2b3E5d825ea88df02EfE) to the [XVS Store](https://etherscan.io/address/0x1Db646E1Ab05571AF99e47e8F909801e5C99d37B), for the new XVS vault rewards.
- **XVS Quarterly Emissions: Bridge 10,584 XVS from the [Core pool Comptroller](https://bscscan.com/address/0xfD36E2c2a6789Db23113685031d7F16329158384) to the [XVS Store](https://etherscan.io/address/0x1Db646E1Ab05571AF99e47e8F909801e5C99d37B) (3,528 XVS/month as per [VIP-471](https://app.venus.io/#/governance/proposal/471)).**
- XVS Vault Speed: Set the new XVS Vault reward speed to **155 daily XVS.**

**Arbitrum one:**

- XVS Buyback Allocation: Send the buyback 120 XVS from the [XVS Vault Treasury](https://arbiscan.io/address/0xb076D4f15c08D7A7B89466327Ba71bc7e1311b58) to the [XVS Store](https://arbiscan.io/address/0x507D9923c954AAD8eC530ed8Dedb75bFc893Ec5e), for the new XVS vault rewards.
- XVS Quarterly Emissions: Bridge 2,205 XVS from the [Core pool Comptroller](https://bscscan.com/address/0xfD36E2c2a6789Db23113685031d7F16329158384) to [XVS Store](https://arbiscan.io/address/0x507D9923c954AAD8eC530ed8Dedb75bFc893Ec5e) (735 XVS/month as per [VIP-471](https://app.venus.io/#/governance/proposal/471)).
- XVS Vault Speed: Set the new XVS Vault reward speed to **26.4 daily XVS.**

**ZKsync Era:**

- Token converters have yet to be deployed for this chain. All allocations for XVS vault rewards for this quarter will be used in the next.
- XVS Quarterly Emissions: Bridge 2,205 XVS from the [Core pool Comptroller](https://bscscan.com/address/0xfD36E2c2a6789Db23113685031d7F16329158384) to [XVS Store](https://explorer.zksync.io/address/0x84266F552756cBed893b1FFA85248cD99501e3ce) (735 XVS/month as per [VIP-471](https://app.venus.io/#/governance/proposal/471)).
- XVS Vault Speed: Maintain the XVS Vault reward speed of **24.2 daily XVS.**

**Unichain:**

- Token converters have yet to be deployed for this chain. All allocations for XVS vault rewards for this quarter will be used in the next.
- XVS Vault Speed: Maintain the XVS Vault reward speed of **6.7 daily XVS** (200 monthly XVS as per [VIP-457](https://app.venus.io/#/governance/proposal/457?chainId=56))**.**

**References**

- [VIP simulation](https://github.com/VenusProtocol/vips/pull/589)
- [Tokenomics V4](https://snapshot.box/#/s:venus-xvs.eth/proposal/0x21c89f6b5d7c9e453b3bac64b23c1d81fe52ff4f23ba0b64674c34217c3f9245)
- [VIP-471 Emissions Adjustments Across All Chains](https://app.venus.io/#/governance/proposal/471?chainId=56)`,
    forDescription: "I agree that Venus Protocol should proceed with this proposal",
    againstDescription: "I do not think that Venus Protocol should proceed with this proposal",
    abstainDescription: "I am indifferent to whether Venus Protocol proceeds or not",
  };

  return makeProposal(
    [
      // Bridge XVS
      {
        target: bscmainnet.UNITROLLER,
        signature: "_grantXVS(address,uint256)",
        params: [bscmainnet.NORMAL_TIMELOCK, TOTAL_XVS],
      },
      {
        target: bscmainnet.XVS,
        signature: "approve(address,uint256)",
        params: [XVS_BRIDGE_BSC, TOTAL_XVS_REMOTE],
      },
      {
        target: bscmainnet.XVS,
        signature: "transfer(address,uint256)",
        params: [XVS_STORE_BSC, XVS_TOTAL_AMOUNT_BSC],
      },
      {
        target: XVS_BRIDGE_BSC,
        signature: "sendFrom(address,uint16,bytes32,uint256,(address,address,bytes))",
        params: [
          bscmainnet.NORMAL_TIMELOCK,
          LzChainId.ethereum,
          ethers.utils.defaultAbiCoder.encode(["address"], [ethereum.VTREASURY]),
          XVS_TOTAL_AMOUNT_ETH,
          [bscmainnet.NORMAL_TIMELOCK, ethers.constants.AddressZero, ADAPTER_PARAMS],
        ],
        value: BRIDGE_FEES.toString(),
      },
      {
        target: XVS_BRIDGE_BSC,
        signature: "sendFrom(address,uint16,bytes32,uint256,(address,address,bytes))",
        params: [
          bscmainnet.NORMAL_TIMELOCK,
          LzChainId.arbitrumone,
          ethers.utils.defaultAbiCoder.encode(["address"], [arbitrumone.VTREASURY]),
          XVS_TOTAL_AMOUNT_ARB,
          [bscmainnet.NORMAL_TIMELOCK, ethers.constants.AddressZero, ADAPTER_PARAMS],
        ],
        value: BRIDGE_FEES.toString(),
      },
      {
        target: XVS_BRIDGE_BSC,
        signature: "sendFrom(address,uint16,bytes32,uint256,(address,address,bytes))",
        params: [
          bscmainnet.NORMAL_TIMELOCK,
          LzChainId.zksyncmainnet,
          ethers.utils.defaultAbiCoder.encode(["address"], [zksyncmainnet.VTREASURY]),
          XVS_TOTAL_AMOUNT_ZKSYNC,
          [bscmainnet.NORMAL_TIMELOCK, ethers.constants.AddressZero, ADAPTER_PARAMS],
        ],
        value: BRIDGE_FEES.toString(),
      },
      {
        target: ethereum.VTREASURY,
        signature: "withdrawTreasuryToken(address,uint256,address)",
        params: [ethereum.XVS, XVS_TOTAL_AMOUNT_ETH, XVS_STORE_ETH],
        dstChainId: LzChainId.ethereum,
      },
      {
        target: arbitrumone.VTREASURY,
        signature: "withdrawTreasuryToken(address,uint256,address)",
        params: [arbitrumone.XVS, XVS_TOTAL_AMOUNT_ARB, XVS_STORE_ARB],
        dstChainId: LzChainId.arbitrumone,
      },
      {
        target: zksyncmainnet.VTREASURY,
        signature: "withdrawTreasuryToken(address,uint256,address)",
        params: [zksyncmainnet.XVS, XVS_TOTAL_AMOUNT_ZKSYNC, XVS_STORE_ZKSYNC],
        dstChainId: LzChainId.zksyncmainnet,
      },

      // Set Emissions
      {
        target: XVS_VAULT_TREASURY_BSC,
        signature: "fundXVSVault(uint256)",
        params: [RELEASE_AMOUNT_BSC],
      },
      {
        target: bscmainnet.XVS_VAULT_PROXY,
        signature: "setRewardAmountPerBlockOrSecond(address,uint256)",
        params: [bscmainnet.XVS, DISTRIBUTION_SPEED_BSC],
      },
      {
        target: XVS_VAULT_TREASURY_ETH,
        signature: "fundXVSVault(uint256)",
        params: [RELEASE_AMOUNT_ETH],
        dstChainId: LzChainId.ethereum,
      },
      {
        target: ethereum.XVS_VAULT_PROXY,
        signature: "setRewardAmountPerBlockOrSecond(address,uint256)",
        params: [ethereum.XVS, DISTRIBUTION_SPEED_ETH],
        dstChainId: LzChainId.ethereum,
      },
      {
        target: XVS_VAULT_TREASURY_ARB,
        signature: "fundXVSVault(uint256)",
        params: [RELEASE_AMOUNT_ARB],
        dstChainId: LzChainId.arbitrumone,
      },
      {
        target: arbitrumone.XVS_VAULT_PROXY,
        signature: "setRewardAmountPerBlockOrSecond(address,uint256)",
        params: [arbitrumone.XVS, DISTRIBUTION_SPEED_ARB],
        dstChainId: LzChainId.arbitrumone,
      },
      {
        target: zksyncmainnet.XVS_VAULT_PROXY,
        signature: "setRewardAmountPerBlockOrSecond(address,uint256)",
        params: [zksyncmainnet.XVS, DISTRIBUTION_SPEED_ZKSYNC],
        dstChainId: LzChainId.zksyncmainnet,
      },
      {
        target: unichainmainnet.XVS_VAULT_PROXY,
        signature: "setRewardAmountPerBlockOrSecond(address,uint256)",
        params: [unichainmainnet.XVS, DISTRIBUTION_SPEED_UNICHAIN],
        dstChainId: LzChainId.unichainmainnet,
      },
    ],
    meta,
    ProposalType.REGULAR,
  );
};

export default vip529;
