import { ethers } from "ethers";
import { NETWORK_ADDRESSES } from "src/networkAddresses";
import { ProposalType } from "src/types";
import { makeProposal } from "src/utils";

import coreMarketOracles from "./data/coreMarketOracles.json";

const { bscmainnet } = NETWORK_ADDRESSES;

export const RESILIENT_ORACLE = bscmainnet.RESILIENT_ORACLE;
export const CHAINLINK_ORACLE = bscmainnet.CHAINLINK_ORACLE;
export const REDSTONE_ORACLE = bscmainnet.REDSTONE_ORACLE;
export const BINANCE_ORACLE = bscmainnet.BINANCE_ORACLE;
export const ATLAS_ORACLE = bscmainnet.ATLAS_ORACLE;
export const COMPTROLLER = bscmainnet.UNITROLLER;
export const VAI = bscmainnet.VAI;

// Atlas VAI/USD feed (Atlas feed id 1049). Atlas pushes on a 24h heartbeat or a 1% deviation,
// so the stale period is the heartbeat plus a 5 minute buffer.
export const VAI_ATLAS_FEED = "0x560fe27da57934EAF2f4107989704EeBd3Da749D";
export const VAI_ATLAS_MAX_STALE_PERIOD = 86700;

export const NEW_VAI_VAULT_RATE = 0;

// Core Pool markets where Atlas is currently the fallback oracle, generated by
// vips/vip-668/scripts/fetchCoreMarketOracles.ts. Each one is today configured as
// [Chainlink, RedStone, Atlas] with every oracle enabled and caching disabled (the script fails
// otherwise). The VIP swaps the pivot and fallback slots and keeps the main oracle, the enable flags
// and the caching flag as is.
export const ATLAS_PIVOT_MARKETS = coreMarketOracles.atlasPivotMarkets;

export const ATLAS_PIVOT_ORACLES = [CHAINLINK_ORACLE, ATLAS_ORACLE, REDSTONE_ORACLE];
export const ATLAS_PIVOT_ENABLE_FLAGS = [true, true, true];

export const VAI_ORACLES = [ATLAS_ORACLE, ethers.constants.AddressZero, ethers.constants.AddressZero];
export const VAI_ENABLE_FLAGS = [true, false, false];

export const vip668 = () => {
  const meta = {
    version: "v2",
    title: "VIP-668 [BNB Chain] Oracle Adjustments and VAI Vault Rewards Stop",
    description: `#### Summary

This proposal makes three operational changes on the BNB Chain Core Pool:

1. Promotes the Atlas oracle to the pivot role for every Core Pool market where it is currently the fallback oracle.
2. Makes Atlas the only price source for VAI.
3. Stops the XVS rewards distributed to the VAI Vault.

#### Atlas as pivot oracle

Atlas is currently the fallback oracle for ${ATLAS_PIVOT_MARKETS.length} Core Pool markets: ${ATLAS_PIVOT_MARKETS.map(
      ({ symbol }) => symbol,
    ).join(
      ", ",
    )}. For each of them this VIP moves Atlas to the pivot slot and moves the current pivot oracle (RedStone) to the fallback slot. The main oracle (Chainlink), the enabled flags and the caching flag stay unchanged. Markets where Atlas is already the main or the pivot oracle are not modified. No feed, stale period or bound is changed.

#### VAI price source

The Atlas oracle has no VAI configuration today, so it is first configured with the Atlas VAI/USD feed (${VAI_ATLAS_FEED}) and a maximum stale period of ${VAI_ATLAS_MAX_STALE_PERIOD} seconds (24 hour heartbeat plus a 5 minute buffer). The ResilientOracle configuration for VAI is then set to Atlas as the main oracle, with no pivot and no fallback oracle. Chainlink and Binance are removed from the VAI price path.

#### VAI Vault rewards

The XVS distribution rate to the VAI Vault is set to 0. The current rate is 341,157,958,083,832 wei of XVS per block (about 65.47 XVS per day). XVS accrued up to the execution block is still released to the VAI Vault by this call, and VAI Vault stakers keep access to rewards already accrued.

#### Actions

1. Calls setTokenConfig((address,address,uint256)) on AtlasOracle (${ATLAS_ORACLE}) for VAI (${VAI}) with the feed and stale period above.
2. Calls setTokenConfig((address,address[3],bool[3],bool)) on ResilientOracle (${RESILIENT_ORACLE}) once per market listed above, setting the oracles to [Chainlink (${CHAINLINK_ORACLE}), Atlas (${ATLAS_ORACLE}), RedStone (${REDSTONE_ORACLE})] with all oracles enabled and caching disabled.
3. Calls setTokenConfig((address,address[3],bool[3],bool)) on ResilientOracle for VAI, setting the oracles to [Atlas, none, none] with only the main oracle enabled and caching disabled.
4. Calls _setVenusVAIVaultRate(uint256) on the Core Pool Comptroller (${COMPTROLLER}) with a rate of 0.`,
    forDescription: "I agree that Venus Protocol should proceed with this proposal",
    againstDescription: "I do not think that Venus Protocol should proceed with this proposal",
    abstainDescription: "I am indifferent to whether Venus Protocol proceeds or not",
  };

  return makeProposal(
    [
      // Atlas feed for VAI, needed before Atlas can be the VAI main oracle
      {
        target: ATLAS_ORACLE,
        signature: "setTokenConfig((address,address,uint256))",
        params: [[VAI, VAI_ATLAS_FEED, VAI_ATLAS_MAX_STALE_PERIOD]],
      },

      // Atlas moves from fallback to pivot, RedStone moves from pivot to fallback
      ...ATLAS_PIVOT_MARKETS.map(({ asset }) => ({
        target: RESILIENT_ORACLE,
        signature: "setTokenConfig((address,address[3],bool[3],bool))",
        params: [[asset, ATLAS_PIVOT_ORACLES, ATLAS_PIVOT_ENABLE_FLAGS, false]],
      })),

      // VAI priced by Atlas only
      {
        target: RESILIENT_ORACLE,
        signature: "setTokenConfig((address,address[3],bool[3],bool))",
        params: [[VAI, VAI_ORACLES, VAI_ENABLE_FLAGS, false]],
      },

      // Stop XVS rewards to the VAI Vault
      {
        target: COMPTROLLER,
        signature: "_setVenusVAIVaultRate(uint256)",
        params: [NEW_VAI_VAULT_RATE],
      },
    ],
    meta,
    ProposalType.REGULAR,
  );
};

export default vip668;
