import { ethers } from "ethers";
import { NETWORK_ADDRESSES } from "src/networkAddresses";
import { ProposalType } from "src/types";
import { makeProposal } from "src/utils";

import coreMarketOracles from "./data/coreMarketOracles.json";

const { bscmainnet } = NETWORK_ADDRESSES;

export const RESILIENT_ORACLE = bscmainnet.RESILIENT_ORACLE;
export const CHAINLINK_ORACLE = bscmainnet.CHAINLINK_ORACLE;
export const REDSTONE_ORACLE = bscmainnet.REDSTONE_ORACLE;
export const BINANCE_ORACLE = bscmainnet.BINANCE_ORACLE;
export const ATLAS_ORACLE = bscmainnet.ATLAS_ORACLE;
export const COMPTROLLER = bscmainnet.UNITROLLER;
export const VAI = bscmainnet.VAI;

// Atlas VAI/USD feed (Atlas feed id 1049). Atlas pushes on a 24h heartbeat or a 1% deviation,
// so the stale period is the heartbeat plus a 5 minute buffer.
export const VAI_ATLAS_FEED = "0x560fe27da57934EAF2f4107989704EeBd3Da749D";
export const VAI_ATLAS_MAX_STALE_PERIOD = 86700;

export const NEW_VAI_VAULT_RATE = 0;

// Core Pool markets where Atlas is currently the fallback oracle, generated by
// vips/vip-668/scripts/fetchCoreMarketOracles.ts. Each one is today configured as
// [Chainlink, RedStone, Atlas] with every oracle enabled and caching disabled (the script fails
// otherwise). The VIP swaps the pivot and fallback slots and keeps the main oracle, the enable flags
// and the caching flag as is.
export const ATLAS_PIVOT_MARKETS = coreMarketOracles.atlasPivotMarkets;

export const ATLAS_PIVOT_ORACLES = [CHAINLINK_ORACLE, ATLAS_ORACLE, REDSTONE_ORACLE];
export const ATLAS_PIVOT_ENABLE_FLAGS = [true, true, true];

export const VAI_ORACLES = [ATLAS_ORACLE, ethers.constants.AddressZero, ethers.constants.AddressZero];
export const VAI_ENABLE_FLAGS = [true, false, false];

export const VTREASURY = bscmainnet.VTREASURY;
export const USDT = "0x55d398326f99059fF775485246999027B3197955";

// TreasuryTokenBuybackDistributor from VIP-646. convertVaiViaPsm() swaps the distributor's whole VAI
// balance for USDT at the VAI PSM and sends the USDT to VTreasury. The PSM fee is paid in VAI and also
// goes to VTreasury.
export const TREASURY_TOKEN_BUYBACK_DISTRIBUTOR = "0xc594053D4b2FaA311b55dDbFAb2338f7c90D6632";
export const VAI_PSM = "0xC138aa4E424D1A8539e8F38Af5a754a2B7c3Cc36";

export const RISK_FUND = "0xdF31a28D68A2AB381D42b380649Ead7ae2A76E42";
// Sells the tokens it holds for USDT and sends the USDT to the RiskFund
export const RISK_FUND_BUYBACK = "0x0c71EFabD00329E839745ef23aB946d3ed24A805";

// RiskFund.sweepToken reverts when the amount is above the balance, so every amount in the three lists
// below is the exact RiskFund balance at block 122009038. BSW and TWT (under $1 each) stay in the RiskFund.
export const LONG_TAIL_TOKENS = [
  { symbol: "FLOKI", address: "0xfb5B838b6cfEEdC2873aB27866079AC55363D37E", amount: "177082682555785184" },
  { symbol: "TRX", address: "0xCE7de646e7208a4Ef112cb6ed5038FA6cC6b12e3", amount: "1833688639" },
  { symbol: "BTT", address: "0x352Cb5E19b12FC216548a2677bD0fce83BaE434B", amount: "1392507212379014539551354602" },
  { symbol: "USDD (old)", address: "0xd17479997F34dd9156Deef8F95A52D81D265be9c", amount: "392463934353680646351" },
  { symbol: "lisUSD", address: "0x0782b6d8c4551B9760e74c0545a9bCD90bdc41E5", amount: "113920863202075023885" },
  { symbol: "TRXOLD", address: "0x85EAC5Ac2F758618dFa09bDbe0cf174e7d574D5B", amount: "15619663448654146823" },
  { symbol: "RACA", address: "0x12BB890508c125661E03b09EC06E404bc9289040", amount: "316724376165504616820380" },
];

// Venus dev recipient used in VIP-628, VIP-641 and VIP-649: receives tokens the proposal cannot convert
// on-chain and works them out off-chain, returning the proceeds to the RiskFund as USDT in a later step.
export const DEV_RECIPIENT = "0x080f8a0fb70f8f0f1b83c6178225a96cbe2be0de";

// The RiskFund buyback prices every token it sells through the ResilientOracle, and getPrice reverts for
// these four: WIN's only oracle is a Chainlink feed that no longer answers, the other three have no oracle
// configuration at all. They go to the dev recipient instead.
export const UNPRICED_TOKENS = [
  { symbol: "WIN", address: "0xaeF0d72a118ce24feE3cD1d43d383897D05B4e99", amount: "1412410526598519969216500" },
  { symbol: "CAT", address: "0x6894CDe390a3f51155ea41Ed24a33A4827d3063D", amount: "12652875825153018355850633" },
  { symbol: "小大力神杯", address: "0x285D6aCC01F38f1Ea4666FA49Ac5f8268d127777", amount: "2020000000000000000000" },
  { symbol: "BRAD", address: "0x3dB1B406a4d50A841948765685ed42ed1f174444", amount: "50000000000000000000000" },
];

// Liquid staking receipt tokens held by the RiskFund, moved whole to the dev recipient for off-chain
// unstaking rather than exited on-chain: the instant exits charge a fee, pay a non-fixed amount of BNB the
// RiskFund cannot receive directly, and the pStake one leaves dust behind.
export const STAKING_RECEIPTS = [
  { symbol: "ankrBNB", address: "0x52F24a5e03aee338Da5fd9Df68D2b6FAe1178827", amount: "2905734451637837137" },
  { symbol: "BNBx", address: "0x1bdd3Cf7F79cfB8EdbB955f20ad99211551BA275", amount: "601110316592232264" },
  { symbol: "stkBNB", address: "0xc2E9d07F66A89c44062459A47a0D2Dc038E4fb16", amount: "208460201756396971" },
  { symbol: "slisBNB", address: "0xB0b84D294e0C75A6abe60171b70edEb2EFd14A1B", amount: "634257472081931688" },
];

export const DEV_RECIPIENT_TOKENS = [...UNPRICED_TOKENS, ...STAKING_RECEIPTS];

export const vip668 = () => {
  const meta = {
    version: "v2",
    title: "VIP-668 [BNB Chain] Oracle Adjustments, VAI Vault Rewards Stop, and Treasury and Risk Fund Cleanup",
    description: `#### Summary

This proposal makes three operational changes on the BNB Chain Core Pool:

1. Promotes the Atlas oracle to the pivot role for every Core Pool market where it is currently the fallback oracle.
2. Makes Atlas the only price source for VAI.
3. Stops the XVS rewards distributed to the VAI Vault.

It also cleans up funds held by the Venus Treasury and the Risk Fund:

4. Converts the VAI held by the Venus Treasury to USDT through the VAI Peg Stability Module (PSM).
5. Sends the long-tail tokens held by the Risk Fund to the RiskFund buyback, which sells them for USDT.
6. Sends the Risk Fund's remaining tokens that the buyback cannot price, and its liquid staking receipt tokens, to the Venus dev recipient for off-chain conversion, with the proceeds returned to the Risk Fund as USDT in a later step.

#### Atlas as pivot oracle

Atlas is currently the fallback oracle for ${ATLAS_PIVOT_MARKETS.length} Core Pool markets: ${ATLAS_PIVOT_MARKETS.map(
      ({ symbol }) => symbol,
    ).join(
      ", ",
    )}. For each of them this VIP moves Atlas to the pivot slot and moves the current pivot oracle (RedStone) to the fallback slot. The main oracle (Chainlink), the enabled flags and the caching flag stay unchanged. Markets where Atlas is already the main or the pivot oracle are not modified. No feed, stale period or bound is changed.

#### VAI price source

The Atlas oracle has no VAI configuration today, so it is first configured with the Atlas VAI/USD feed (${VAI_ATLAS_FEED}) and a maximum stale period of ${VAI_ATLAS_MAX_STALE_PERIOD} seconds (24 hour heartbeat plus a 5 minute buffer). The ResilientOracle configuration for VAI is then set to Atlas as the main oracle, with no pivot and no fallback oracle. Chainlink and Binance are removed from the VAI price path.

After this change VAI has a single price source. There is no pivot oracle to cross validate the Atlas price and no fallback oracle to take over. If Atlas stops pushing the VAI price for more than ${VAI_ATLAS_MAX_STALE_PERIOD} seconds, getPrice reverts for VAI, and every operation that prices VAI, including minting, repaying and liquidating VAI, reverts with it until a new price is pushed.

#### VAI Vault rewards

The XVS distribution rate to the VAI Vault is set to 0. The current rate is 341,157,958,083,832 wei of XVS per block (about 65.47 XVS per day). Before the rate is updated, the Comptroller releases the XVS accrued since the last release to the VAI Vault, provided that amount reaches the Comptroller's minimum release amount of 4 XVS; a smaller amount stays in the Comptroller. VAI Vault stakers keep access to rewards already accrued.

#### Treasury VAI

The Venus Treasury holds about 2,343.39 VAI. The whole balance is withdrawn to the TreasuryTokenBuybackDistributor (${TREASURY_TOKEN_BUYBACK_DISTRIBUTOR}, used in VIP-646), and convertVaiViaPsm() swaps it for USDT at the VAI PSM (${VAI_PSM}). The USDT goes back to the Venus Treasury. The PSM charges a 0.1% fee, paid in VAI, which also goes to the Venus Treasury. At the time of writing the swap returns about 2,341.05 USDT.

convertVaiViaPsm() is best effort. It wraps the PSM swap in a try/catch, so if the PSM cannot serve the swap at execution time, for example while it is paused or while its USDT price is stale, the call does not revert and the rest of the proposal still executes. In that case the VAI stays in the TreasuryTokenBuybackDistributor instead of returning to the Venus Treasury as USDT. A successful conversion emits one VaiConvertedViaPsm event, which should be checked in the execution receipt.

#### Risk Fund long-tail tokens

The Risk Fund (${RISK_FUND}) holds these tokens outside its base assets. Each one is sent to the RiskFund buyback (${RISK_FUND_BUYBACK}), which sells it for USDT and sends the USDT to the Risk Fund:

- FLOKI: 177,082,682.56 (about $4,298)
- TRX: 1,833.69 (about $619)
- BTT: 1,392,507,212.38 (about $460)
- USDD (old): 392.46 (about $391)
- lisUSD: 113.92 (about $114)
- TRXOLD: 15.62 (about $5)
- RACA: 316,724.38 (about $4)

BSW and TWT are worth less than $1 each and are not moved.

#### Risk Fund tokens the buyback cannot price

The RiskFund buyback prices every token it sells through the Resilient Oracle. getPrice reverts for the four tokens below, so the buyback cannot value them: the only oracle configured for WIN is Chainlink, whose WIN feed no longer responds, and the other three have no oracle configuration. Each one is sent whole to the Venus dev recipient (${DEV_RECIPIENT}, also used in VIP-628, VIP-641 and VIP-649), which converts it off-chain and returns the proceeds to the Risk Fund as USDT in a later step:

- WIN: 1,412,410.53 (about $53)
- CAT: 12,652,875.83 (about $25)
- 小大力神杯: 2,020 (about $6)
- BRAD: 50,000 (about $3)

#### Risk Fund staking positions

The Risk Fund holds receipt tokens from four liquid staking protocols. Each one is sent whole to the same Venus dev recipient, which unstakes it off-chain and returns the proceeds to the Risk Fund as USDT in a later step:

- ankrBNB: 2.9057 (about $2,311)
- BNBx: 0.6011 (about $479)
- stkBNB: 0.2085 (about $157)
- slisBNB: 0.6343 (about $473)

The positions are not exited on-chain in this proposal. The instant exits charge a fee (0.25% on Ankr), pay an amount of BNB that is only known at execution and that the Risk Fund cannot receive directly, the pStake pool only accepts multiples of 1e12 wei and would leave dust behind, and Lista's instant withdrawal is limited to whitelisted accounts. Moving the receipt tokens whole avoids all of that and keeps the proposal independent of the state of those protocols at execution.

#### Actions

1. Calls setTokenConfig((address,address,uint256)) on AtlasOracle (${ATLAS_ORACLE}) for VAI (${VAI}) with the feed and stale period above.
2. Calls setTokenConfig((address,address[3],bool[3],bool)) on ResilientOracle (${RESILIENT_ORACLE}) once per market listed above, setting the oracles to [Chainlink (${CHAINLINK_ORACLE}), Atlas (${ATLAS_ORACLE}), RedStone (${REDSTONE_ORACLE})] with all oracles enabled and caching disabled.
3. Calls setTokenConfig((address,address[3],bool[3],bool)) on ResilientOracle for VAI, setting the oracles to [Atlas, none, none] with only the main oracle enabled and caching disabled.
4. Calls _setVenusVAIVaultRate(uint256) on the Core Pool Comptroller (${COMPTROLLER}) with a rate of 0.
5. Calls withdrawTreasuryBEP20(address,uint256,address) on VTreasury (${VTREASURY}) for the whole VAI balance, to the TreasuryTokenBuybackDistributor.
6. Calls convertVaiViaPsm() on the TreasuryTokenBuybackDistributor.
7. Calls sweepToken(address,address,uint256) on the Risk Fund once per long-tail token listed above, to the RiskFund buyback.
8. Calls sweepToken(address,address,uint256) on the Risk Fund once per token the buyback cannot price (WIN, CAT, 小大力神杯, BRAD), to the Venus dev recipient.
9. Calls sweepToken(address,address,uint256) on the Risk Fund once per staking receipt token (ankrBNB, BNBx, stkBNB, slisBNB), to the Venus dev recipient.`,
    forDescription: "I agree that Venus Protocol should proceed with this proposal",
    againstDescription: "I do not think that Venus Protocol should proceed with this proposal",
    abstainDescription: "I am indifferent to whether Venus Protocol proceeds or not",
  };

  return makeProposal(
    [
      // Atlas feed for VAI, needed before Atlas can be the VAI main oracle
      {
        target: ATLAS_ORACLE,
        signature: "setTokenConfig((address,address,uint256))",
        params: [[VAI, VAI_ATLAS_FEED, VAI_ATLAS_MAX_STALE_PERIOD]],
      },

      // Atlas moves from fallback to pivot, RedStone moves from pivot to fallback
      ...ATLAS_PIVOT_MARKETS.map(({ asset }) => ({
        target: RESILIENT_ORACLE,
        signature: "setTokenConfig((address,address[3],bool[3],bool))",
        params: [[asset, ATLAS_PIVOT_ORACLES, ATLAS_PIVOT_ENABLE_FLAGS, false]],
      })),

      // VAI priced by Atlas only
      {
        target: RESILIENT_ORACLE,
        signature: "setTokenConfig((address,address[3],bool[3],bool))",
        params: [[VAI, VAI_ORACLES, VAI_ENABLE_FLAGS, false]],
      },

      // Stop XVS rewards to the VAI Vault
      {
        target: COMPTROLLER,
        signature: "_setVenusVAIVaultRate(uint256)",
        params: [NEW_VAI_VAULT_RATE],
      },

      // Treasury VAI to USDT through the PSM, USDT goes back to VTreasury
      {
        target: VTREASURY,
        signature: "withdrawTreasuryBEP20(address,uint256,address)",
        params: [VAI, ethers.constants.MaxUint256, TREASURY_TOKEN_BUYBACK_DISTRIBUTOR],
      },
      {
        target: TREASURY_TOKEN_BUYBACK_DISTRIBUTOR,
        signature: "convertVaiViaPsm()",
        params: [],
      },

      // Long-tail tokens to the RiskFund buyback, sold for USDT
      ...LONG_TAIL_TOKENS.map(({ address, amount }) => ({
        target: RISK_FUND,
        signature: "sweepToken(address,address,uint256)",
        params: [address, RISK_FUND_BUYBACK, amount],
      })),

      // Tokens the buyback cannot price and the staking receipt tokens, whole to the dev recipient for
      // off-chain conversion
      ...DEV_RECIPIENT_TOKENS.map(({ address, amount }) => ({
        target: RISK_FUND,
        signature: "sweepToken(address,address,uint256)",
        params: [address, DEV_RECIPIENT, amount],
      })),
    ],
    meta,
    ProposalType.REGULAR,
  );
};

export default vip668;
